apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-api-jannin
  labels:
    app: sample-api-jannin
    component: api
spec:
  scaleTargetRef:
    kind: Deployment
    name: sample-api-jannin
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
