apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: micro-jannin

commonLabels:
  app: sample-api-jannin

configMapGenerator:
- name: sample-api-jannin
  envs:
  - variables.properties

resources:
- deployment.yaml
- service.yaml
- hpa.yaml

commonAnnotations:
  product: semillero
